version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: gresau/localstack-persist
    ports:
      - "4566:4566"
    environment:
      - DEBUG=${DEBUG:-1}
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:3001
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1
    volumes:
      - "../my-localstack-data:/persisted-data"
      - "/var/run/docker.sock:/var/run/docker.sock"
